---
# tasks file for mshurutov.postgres_schedule
- name: Check if ansible version is equal or greater than 2.11
  ansible.builtin.fail:
    msg: "Ansible core should be equal or greater than 2.11"
  when: ansible_version.full is ansible.builtin.version('2.11','<')
- name: Check if python is equal or greater than 3
  ansible.builtin.fail:
    msg: "Python should be equal or greater than 3"
  when: ansible_python.version.major is ansible.builtin.version('3','<')

- name: Install packages
  become: true
  become_user: "root"
  tags: postgres_schedule_install
  notify:
    - "Systemd daemon-reload"
    - "Enable {{ postgres_schedule_package }}"
    - "Start {{ postgres_schedule_package }}"
  block:
    - name: Check if necessary repo is added
      when: ansible_pkg_mgr == "apt" or ansible_pkg_mgr == "apt_rpm"
      ansible.builtin.include_role:
        name: "mshurutov.common"
        tasks_from: "{{ ansible_pkg_mgr }}-repo-add.yml"
    - name: Install packages on normal distro
      when: ansible_pkg_mgr != "apt_rpm"
      ansible.builtin.package:
        name: "{{ postgres_schedule_package }}"
        state: present
    - name: Install packages on normal distro
      when: ansible_pkg_mgr == "apt_rpm"
      ansible.builtin.package:
        name: "{{ postgres_schedule_package }}"
        state: present_not_latest

- name: Check if postgres schedule config dir exists
  become: true
  become_user: "{{ postgres_system_user }}"
  tags: postgres_schedule_config,postgres_schedule_config_dir
  ansible.builtin.file:
    group: "{{ postgres_system_user }}"
    mode: "0700"
    owner: "{{ postgres_system_user }}"
    path: "{{ postgres_schedule_config_dir }}"
    state: "directory"

- name: Install config for postgres scheduler
  become: true
  become_user: "{{ postgres_system_user }}"
  tags: postgres_schedule_config,postgres_schedule_config_files
  ansible.builtin.template:
    dest: "{{ postgres_schedule_config_dir }}/{{ item.name }}"
    group: "{{ postgres_system_user }}"
    mode: "0600"
    owner: "{{ postgres_system_user }}"
    src: "{{ postgres_schedule_templates_path }}/{{ postgres_schedule_package }}.conf.j2"
  loop: "{{ postgres_scheduler }}"

- name: Check if postgres_schedule user is in ~/.pgpass
  become: true
  become_user: "{{ postgres_system_user }}"
  tags: postgres_schedule_config,pgpass
  ansible.builtin.lineinfile:
    path: "{{ postgres_home_dir }}/.pgpass"
    line: "{{ item.1 }}:*:*:{{ item.0.pguser }}:{{ item.0.pgpassword }}"
    owner: "{{ postgres_system_user }}"
    group: "{{ postgres_system_user }}"
    mode: "0600"
    create: true
    state: "present"
  loop: "{{ postgres_scheduler | product([common_ip4_default, '127.0.0.1']) }}"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Add jobs into postgres scheduler
  become: true
  become_user: "{{ postgres_system_user }}"
  tags: postgres_schedule_jobs
  community.postgresql.postgresql_query:
    login_host: "127.0.0.1"
    login_user: "{{ item.0.pguser }}"
    db: "{{ item.0.dbname }}"
    query: "{{ item.1.query }}"
    search_path: "{{ item.1.search_path | default(omit) }}"
    session_role: "{{ item.0.pguser }}"
  loop: "{{ postgres_scheduler | subelements('jobs', skip_missing=True) }}"
