---
# handlers file for mshurutov.postgres_schedule
- name: Systemd daemon-reload
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Enable pg_timetable
  ansible.builtin.systemd_service:
    enabled: true
    name: "pg_timetable@{{ item.name }}"
  loop: "{{ postgres_scheduler }}"

- name: Start pg_timetable
  ansible.builtin.systemd_service:
    name: "pg_timetable@{{ item.name }}"
    state: started
  loop: "{{ postgres_scheduler }}"
